yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ hapi-swagger@16.0.1
info All dependencies
└─ hapi-swagger@16.0.1
Done in 8.32s.
